ALTER TABLE sys_user ADD COLUMN last_login_at TEXT NOT NULL DEFAULT '';
ALTER TABLE sys_user ADD COLUMN session_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sys_role ADD COLUMN is_builtin INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sys_audit_log ADD COLUMN before_json TEXT NOT NULL DEFAULT '';
ALTER TABLE sys_audit_log ADD COLUMN after_json TEXT NOT NULL DEFAULT '';
