-- One-time data fix: void older duplicate approved offer records for the same application.
-- Run manually after verifying candidate/application IDs.
--
-- Example (朱沿峰, application_id=30): find duplicates, then supersede the older row:
--
-- SELECT r.id, r.application_id, r.status, c.name, r.created_at
-- FROM rms_offer_records r
-- JOIN rms_applications a ON a.id = r.application_id
-- JOIN rms_candidates c ON c.id = a.candidate_id
-- WHERE c.name LIKE '%朱沿峰%' AND r.status = 'approved'
-- ORDER BY r.application_id, r.id;
--
-- UPDATE rms_offer_records
-- SET status = 'superseded',
--     reason = 'duplicate_approved_voided',
--     current_approval_node = '',
--     updated_at = date('now')
-- WHERE id = 10 AND application_id = 30 AND status = 'approved';
