"""Delivery Interviews constants and schema definitions (Phase 5C)."""
from __future__ import annotations

INTERVIEW_EXPORT_HEADERS = [
    "序号",
    "员工姓名",
    "在职/离职",
    "联系方式",
    "所属项目",
    "岗位",
    "员工加1",
    "入职时间",
    "访谈日期",
    "满意度",
    "交付判断",
    "员工诉求",
    "交付待办事项",
    "工作地",
    "老家",
    "1 D",
    "7 D",
    "30 D",
    "90 D",
]

INTERVIEW_HEADER_MAP = {
    "序号": "serial_no",
    "员工姓名": "full_name",
    "在职/离职": "employment_status",
    "联系方式": "contact",
    "所属项目": "project_name",
    "岗位": "position",
    "员工加1": "employee_q1",
    "员工+1": "employee_q1",
    "员工＋1": "employee_q1",
    "员工➕1": "employee_q1",
    "员工加Q1": "employee_q1",
    "员工ID": "employee_q1",
    "入职时间": "onboarding_time",
    "访谈日期": "interview_date",
    "满意度": "satisfaction",
    "入职天数": "days_since_onboarding",
    "访谈内容及情况": "interview_content",
    "交付判断": "delivery_judgment",
    "员工诉求": "employee_requests",
    "交付待办事项": "delivery_todos",
    "工作地": "work_location",
    "老家": "hometown",
    "1 D": "followup_1d",
    "7 D": "followup_7d",
    "30 D": "followup_30d",
    "90 D": "followup_90d",
}

INTERVIEW_IMPORT_ALIASES = {
    "姓名": "full_name",
    "被访谈人": "full_name",
    "候选人": "full_name",
    "面谈日期": "interview_date",
    "访谈时间": "interview_date",
    "日期": "interview_date",
    "时间": "interview_date",
    "业务部门": "project_name",
    "项目组": "project_name",
    "项目": "project_name",
    "分部": "project_name",
    "工种": "position",
    "职务": "position",
    "手机号": "contact",
    "电话": "contact",
    "手机": "contact",
    "司龄天数": "days_since_onboarding",
    "入职日": "onboarding_time",
    "访谈内容": "interview_content",
    "谈话内容": "interview_content",
    "面谈记录": "interview_content",
    "内容": "interview_content",
    "记录": "interview_content",
    "摘要": "interview_content",
    "状态": "employment_status",
    "籍贯": "hometown",
    "地点": "work_location",
    "城市": "work_location",
    "改进措施": "delivery_todos",
    "待办事项": "delivery_todos",
    "1d": "followup_1d",
    "7d": "followup_7d",
    "30d": "followup_30d",
    "90d": "followup_90d",
}
