"""Delivery Pipeline constants — migrated from main.py (Phase 5B)."""
from __future__ import annotations

PIPELINE_EXPORT_HEADERS = [
    "简历时间",
    "日期",
    "岗位",
    "姓名",
    "领域",
    "年限",
    "地域",
    "电话",
    "学历",
    "招聘",
    "简历筛选",
    "是否面试",
    "面试时间",
    "面试官",
    "面试结果",
    "是否拿offer",
    "入职时间",
    "是否入职",
    "情况",
    "序号",
]

PIPELINE_HEADER_MAP = {
    "简历时间": "resume_time",
    "日期": "date",
    "岗位": "position",
    "姓名": "full_name",
    "领域": "domain",
    "年限": "years_experience",
    "地域": "region",
    "电话": "phone",
    "学历": "education",
    "招聘": "recruiter",
    "简历筛选": "resume_screening",
    "是否面试": "interviewed",
    "面试时间": "interview_time",
    "面试官": "interviewer",
    "结果": "result",
    "面试结果": "result",
    "是否拿offer": "got_offer",
    "入职时间": "onboarding_time",
    "是否入职": "onboarded",
    "情况": "status_note",
    "序号": "serial_no",
}

PIPELINE_IMPORT_HEADER_ALIASES = {
    "姓名": "full_name",
    "候选人": "full_name",
    "候选人姓名": "full_name",
    "工作地": "region",
    "地区": "region",
    "城市": "region",
    "手机号": "phone",
    "联系电话": "phone",
    "工作年限": "years_experience",
    "经验年限": "years_experience",
    "筛选结果": "resume_screening",
    "简历筛选结果": "resume_screening",
    "是否拿offer": "got_offer",
    "是否接offer": "got_offer",
    "是否拿到offer": "got_offer",
    "拿offer": "got_offer",
    "状态": "status_note",
    "备注": "status_note",
    "面试结果": "result",
}
