"""Delivery Roster domain constants and field mappings."""
from __future__ import annotations

from typing import Tuple

ROSTER_FIELD_KEYS = frozenset(
    [
        "serial_no",
        "employment_status",
        "full_name",
        "contact_info",
        "customer_name",
        "work_location",
        "position_title",
        "business_line",
        "entry_date",
        "regularization_status",
        "throme_staff_no",
        "regularization_date",
        "quote_unit",
        "quote_amount_tax",
        "monthly_billable_days",
        "daily_billable_hours",
        "monthly_quote_tax",
        "pre_tax_salary",
        "salary_quote_ratio",
        "gms",
        "gm_pct",
        "employee_plus1",
        "zntx_onboarding_channel",
        "zntx_attendance_checkin",
        "zntx_attendance_makeup",
        "employee_plus2",
        "interface_contact",
        "project_release_date",
        "company_resign_date",
        "zntx_staff_no",
        "zntx_separation_type",
        "zntx_compensation_amount",
        "delivery_communication",
        "business_action",
        "bp_involved",
        "leave_reason",
        "remarks",
    ]
)


CHINESE_ROSTER_HEADER_MAP = {
    "序号": "serial_no",
    "在职情况": "employment_status",
    "姓名": "full_name",
    "联系方式": "contact_info",
    "客户": "customer_name",
    "工作地": "work_location",
    "岗位": "position_title",
    "业务线": "business_line",
    "项目": "business_line",
    "入职日期": "entry_date",
    "入职时间": "entry_date",
    "转正": "regularization_status",
    "转正时间": "regularization_date",
    "月报价(含税)": "monthly_quote_tax",
    "报价（含税）": "monthly_quote_tax",
    "报价": "monthly_quote_tax",
    "税前工资": "pre_tax_salary",
    "薪资": "pre_tax_salary",
    "薪资报价比": "salary_quote_ratio",
    "报价系数": "salary_quote_ratio",
    "GM$": "gms",
    "GMS": "gms",
    "GM%": "gm_pct",
    "员工+1": "employee_plus1",
    "员工加1": "employee_plus1",
    "入职渠道": "zntx_onboarding_channel",
    "打卡": "zntx_attendance_checkin",
    "补卡": "zntx_attendance_makeup",
    "员工+2": "employee_plus2",
    "接口": "interface_contact",
    "项目释放日期": "project_release_date",
    "项目释放时间": "project_release_date",
    "公司离职日期": "company_resign_date",
    "离职时间": "company_resign_date",
    "主动/被动": "zntx_separation_type",
    "主动被动": "zntx_separation_type",
    "工号": "zntx_staff_no",
    "中诺工号": "zntx_staff_no",
    "中河工号": "zntx_staff_no",
    "离职类型": "zntx_separation_type",
    "补偿金": "zntx_compensation_amount",
    "薪酬金": "zntx_compensation_amount",
    "交付沟通": "delivery_communication",
    "业务处理动作": "business_action",
    "BP参与与否": "bp_involved",
    "BP参与": "bp_involved",
    "BP参与动作": "bp_involved",
    "bp参与动作": "bp_involved",
    "离职或释放原因": "leave_reason",
    "离职和离职原因": "leave_reason",
    "释放/离职原因": "leave_reason",
    "释放成功离职原因": "leave_reason",
    "备注": "remarks",
}


ROSTER_CUSTOMER_ALIAS_RULES: Tuple[Tuple[str, str], ...] = (
    ("远景智能", "远景智能"),
    ("中诺", "中诺通讯"),
    ("华勤", "华勤科技"),
    ("帷幄", "帷幄科技"),
    ("日产", "日产中国"),
    ("元枢", "元枢智汇"),
)


ROSTER_CREATE_REQUIRED_FIELDS = (
    "employment_status",
    "full_name",
    "contact_info",
    "customer_name",
    "work_location",
    "position_title",
    "business_line",
    "entry_date",
    "regularization_status",
    "quote_amount_tax",
    "pre_tax_salary",
    "gms",
    "gm_pct",
)


ROSTER_REQUIRED_LABELS = {
    "employment_status": "在职情况",
    "full_name": "姓名",
    "contact_info": "联系方式",
    "customer_name": "客户",
    "work_location": "工作地",
    "position_title": "岗位",
    "business_line": "业务线",
    "entry_date": "入职时间",
    "regularization_status": "转正",
    "quote_amount_tax": "报价(含税)",
    "pre_tax_salary": "税前工资",
    "gms": "GM$",
    "gm_pct": "GM%",
}


ROSTER_EXPORT_HEADERS = [
    "序号",
    "在职情况",
    "姓名",
    "工号",
    "联系方式",
    "客户",
    "工作地",
    "岗位",
    "业务线",
    "入职日期",
    "转正",
    "转正时间",
    "月报价(含税)",
    "税前工资",
    "报价系数",
    "GM$",
    "GM%",
    "员工+1",
    "入职渠道",
    "员工+2",
    "接口",
    "项目释放日期",
    "公司离职日期",
    "离职或释放原因",
    "交付沟通",
    "业务处理动作",
    "BP参与与否",
    "备注",
]


ZNTX_ROSTER_EXPORT_HEADERS = [
    "序号",
    "在职情况",
    "姓名",
    "工号",
    "联系方式",
    "客户",
    "工作地",
    "岗位",
    "业务线",
    "入职时间",
    "转正",
    "转正时间",
    "月报价(含税)",
    "税前工资",
    "报价系数",
    "GM$",
    "GM%",
    "员工+1",
    "入职渠道",
    "打卡",
    "员工+2",
    "接口",
    "交付沟通",
    "业务处理动作",
    "BP参与与否",
    "备注",
]
